server:
  port: 8081
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: eureka-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.16.178:3306/seata?rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      idle-timeout: 6000
      minimum-idle: 2
      maximum-pool-size: 10
      pool-name: HikariCP
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    io.seata: debug
    com.xxx.provider: debug
seata:
  tx-service-group: seata-demo-group