server:
  port: 8081
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: eureka-provider
  cloud:
    alibaba:
      seata:
        tx-service-group: seata-demo-group
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    io.seata: debug