server:
  port: 9102
graphql:
  servlet:
    mapping: /graphql
    corsEnabled: false
    enabled: true
  tools:
    schema-location-pattern: "schema/*.graphqls"
spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: false