server:
  port: 8082
eureka:
  client:
    register-with-eureka: false
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: eureka-consumer
  jpa:
    show-sql: true
  cloud:
    alibaba:
      seata:
        tx-service-group: seata-demo-group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.16.178:3306/seata?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      idle-timeout: 6000
      minimum-idle: 2
      maximum-pool-size: 10
      pool-name: HikariCP
    type: com.zaxxer.hikari.HikariDataSource
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    io.seata: debug