server:
  port: 8080
  servlet:
    context-path: /
graphql:
  servlet:
    mapping: /graphql
    corsEnabled: false
    enabled: true
  tools:
    schema-location-pattern: "schema/*.graphqls"
#    playground:
#      cdn:
#        enabled: true
spring:
  mvc:
    static-path-pattern: /**